### ISSUE TITLE
Synchronizuj kanały płatności - błąd

### ISSUE THREAD

**Issue by tgozdziewski** [bluepayment-plugin/magento-2.x-plugin#11]
Wersja modułu: 2.22.6

`TypeError: BlueMedia\BluePayment\Model\Gateway::setLogoUrl(): Argument #1 ($logoUrl) must be of type string, null given, called in /home/magento/www/vendor/bluepayment-plugin/module-bluepayment/Helper/Gateways.php on line 294 and defined in /home/magento/www/vendor/bluepayment-plugin/module-bluepayment/Model/Gateway.php:290
Stack trace:
#0 /home/magento/www/vendor/bluepayment-plugin/module-bluepayment/Helper/Gateways.php(294): BlueMedia\BluePayment\Model\Gateway->setLogoUrl()
#1 /home/magento/www/vendor/bluepayment-plugin/module-bluepayment/Helper/Gateways.php(152): BlueMedia\BluePayment\Helper\Gateways->saveGateways()
#2 /home/magento/www/vendor/bluepayment-plugin/module-bluepayment/Controller/Adminhtml/Gateway/Synchronize.php(50): BlueMedia\BluePayment\Helper\Gateways->syncGateways()
#3 /home/magento/www/vendor/magento/framework/Interception/Interceptor.php(58): BlueMedia\BluePayment\Controller\Adminhtml\Gateway\Synchronize->execute()
#4 /home/magento/www/vendor/magento/framework/Interception/Interceptor.php(138): BlueMedia\BluePayment\Controller\Adminhtml\Gateway\Synchronize\Interceptor->___callParent()
#5 /home/magento/www/vendor/magento/framework/Interception/Interceptor.php(153): BlueMedia\BluePayment\Controller\Adminhtml\Gateway\Synchronize\Interceptor->Magento\Framework\Interception\{closure}()
#6 /home/magento/www/generated/code/BlueMedia/BluePayment/Controller/Adminhtml/Gateway/Synchronize/Interceptor.php(23): BlueMedia\BluePayment\Controller\Adminhtml\Gateway\Synchronize\Interceptor->___callPlugins()
#7 /home/magento/www/vendor/magento/framework/App/Action/Action.php(111): BlueMedia\BluePayment\Controller\Adminhtml\Gateway\Synchronize\Interceptor->execute()
#8 /home/magento/www/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#9 /home/magento/www/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#10 /home/magento/www/vendor/magento/framework/Interception/Interceptor.php(138): BlueMedia\BluePayment\Controller\Adminhtml\Gateway\Synchronize\Interceptor->___callParent()
#11 /home/magento/www/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): BlueMedia\BluePayment\Controller\Adminhtml\Gateway\Synchronize\Interceptor->Magento\Framework\Interception\{closure}()
#12 /home/magento/www/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#13 /home/magento/www/vendor/magento/framework/Interception/Interceptor.php(153): BlueMedia\BluePayment\Controller\Adminhtml\Gateway\Synchronize\Interceptor->Magento\Framework\Interception\{closure}()
#14 /home/magento/www/generated/code/BlueMedia/BluePayment/Controller/Adminhtml/Gateway/Synchronize/Interceptor.php(32): BlueMedia\BluePayment\Controller\Adminhtml\Gateway\Synchronize\Interceptor->___callPlugins()
#15 /home/magento/www/vendor/magento/framework/App/FrontController.php(245): BlueMedia\BluePayment\Controller\Adminhtml\Gateway\Synchronize\Interceptor->dispatch()
#16 /home/magento/www/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#17 /home/magento/www/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#18 /home/magento/www/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#19 /home/magento/www/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#20 /home/magento/www/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#21 /home/magento/www/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#22 /home/magento/www/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#23 /home/magento/www/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#24 /home/magento/www/pub/index.php(55): Magento\Framework\App\Bootstrap->run()
#25 {main}`

Rozwiązaniem jest modyfikacja w pliku:
vendor/bluepayment-plugin/module-bluepayment/Helper/Gateways.php

Linia 294:
Zamiast:
`$gatewayModel->setLogoUrl($gateway['iconURL'] ?? null);`
Powinno być:
`$gatewayModel->setLogoUrl($gateway['iconURL'] ?? '');`

https://github.com/bluepayment-plugin/magento-2.x-plugin/blob/3d19020a0618ae14250d061e4763e30350e169c2/Helper/Gateways.php#L294

**Comment by zalazdi** [comment]
@tgozdziewski 
Poprawka będzie umieszczona w następnej wersji modułu.

Mogę prosić tylko o informację, czy błąd wystąpił z bramką produkcyjną czy testową?
Produkcyjnie - wszystkie kanały powinny mieć ustalony logotyp, stąd jeśli tam to wystąpiło - będziemy problem szerzej weryfikowali również na bramce.

**Comment by tgozdziewski** [comment]
@zalazdi 

Na testowym.

**Comment by zalazdi** [comment]
@tgozdziewski 
Najnowsza wersja modułu zawiera już poprawkę do tego problemu.
